# should enable addons ingress
# type "minikube addons enable ingress" in console to enable that.
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hello-ingress-workshop1
  namespace: workshop1
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: workshop1.localhost
    http:
      paths:
      - pathType: Prefix
        path: /workshop1
        backend:
          service:
            name: spring-boot-service
            port:
              number: 9091